#!/bin/bash
rm -r ../horse_art/32px-der/*
rm -r ../horse_art/16px-der/*
python3 scripts/image_size.py "../horse_art"
rm -r src/main/resources/assets/horse_colors/textures/*
cp -r ../horse_art/16px-der/* src/main/resources/assets/horse_colors/textures/
cp -r ../horse_art/16px-src/* src/main/resources/assets/horse_colors/textures/
cp -r ../horse_art/16px-unq/* src/main/resources/assets/horse_colors/textures/
